# Generated by Django 3.2.13 on 2022-06-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_auto_20220618_1456"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"permissions": [("view_history", "Can view history")]},
        ),
    ]
