# Generated by Django 3.2.13 on 2022-06-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_producrimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProducrImages',
            new_name='ProductImages',
        ),
    ]
